application: steady-dryad-577
version: 1
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /
  script: room_selector.py
- url: /.*
  script: room.py

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest